[package]
name = "minifier"
version = "0.1.0"
authors = ["Carter Snook <cartersnook04@gmail.com>"]
edition = "2018"

[dependencies]
parser = { path = "../parser" }
itertools = "0.10.1"
vex = { path = "../vex" }
