[package]
name = "vex"
version = "0.1.0"
authors = ["Carter Snook <cartersnook04@gmail.com>"]
edition = "2018"

[dependencies]
parser = { path = "../parser" }

[dev-dependencies]
minifier = { path = "../minifier" }
